### ISSUE TITLE
dominance signaling

### ISSUE THREAD

**Issue by yellowcakorn** [carnistclaims/carnistclaims.github.io#3]
your rebuttals are infused with poison, as if you think you're directly addressing the people making these arguments. you know that 90% of the people visiting this site will be fellow vegans, right? even if a carnist somehow found their way here, they would probably just skim through a few articles then leave.

you've mentioned more than once that you have a PhD. why? if it was in ethics or agricultural science or something like that, but it's in field almost entirely unrelated to veganism. call me cynical, but the only reason I can think that someone might do that is if they wanted to let the reader know that they're smarter than them.

**Comment by carnistclaims** [comment]
Hmm yeah this is a good perspective and I've been thinking about this for the last day since you posted this. I sort of started this with the idea that it was going to be more or less how I respond to posts on reddit and elsewhere which I guess should be more informative and reserved and less in response to the other person. It's better to drop facts and then the mic rather than inject invective dialog into these pages. 

I guess subconsciously I assume that if it's not combative (and is more passive), people will listen more.... but that's probably not the case, so tone definitely deserves second thought, especially considering most of the competing sites don't follow the style I sort of chose for myself.

**Comment by carnistclaims** [comment]
I'm working through the old content. I appreciate the input and am working to improve all the pages that I already have up.

Thanks for helping improve the site
